TMP102 Temp sensor arduino code
frc2357/robotlib2357 pull request #97
Opened 2023-01-14 19:12 UTC by JCGWE30

2023-01-14 19:23 UTC, NolanCampbell2357 requested changes

2023-01-14 19:23 UTC, NolanCampbell2357 commented on arduino/sensors/TMP102_TempatureSensor/TMP102_TempatureSensor.ino
> +const int ALERT_PIN = A3;
This should be under you includes, additionaly if you want to be more memory efficient you can use the preprocessor directive `#define` followed by your variable name `ALERT_PIN` then set your pin on it. The end result should be `#define ALERT_PIN A3`

2023-01-14 19:23 UTC, NolanCampbell2357 commented on arduino/sensors/TMP102_TempatureSensor/TMP102_TempatureSensor.ino
> +TMP102 sensor0;
let's rename this to a less-vague name. Next year when we train the new students we do not want to confuse them with vague sensor names. Maybe try `tempSensor` just to make sure we know what the sensor is doing.

2023-01-14 19:37 UTC, NolanCampbell2357 approved these changes

2023-01-14 19:44 UTC, merged

2023-01-30 20:08 UTC, coderkevin commented on arduino/sensors/TMP102_TempatureSensor/TMP102_TempatureSensor.ino
> +  device.initSensor("floatValue", readFloatValue);
Just a note here. I'm thinking the name of this sensor value should be more descriptive like "tempCelsius" or the like (assuming the reading is in celsius.